const timezones = [
  { shortCode: 'UTC', expansion: 'Universal Time' },
  { shortCode: 'GMT', expansion: 'Greenwich Mean Time' },
  { shortCode: 'BST', expansion: 'British Summer Time' },
  { shortCode: 'EST', expansion: 'Eastern Standard Time' },
  { shortCode: 'EDT', expansion: 'Eastern Daylight Time' },
  { shortCode: 'CST', expansion: 'Central Standard Time' },
  { shortCode: 'CDT', expansion: 'Central Daylight Time' },
  { shortCode: 'MST', expansion: 'Mountain Standard Time' },
  { shortCode: 'MDT', expansion: 'Mountain Daylight Time' },
  { shortCode: 'PST', expansion: 'Pacific Standard Time' },
  { shortCode: 'PDT', expansion: 'Pacific Daylight Time' },
  { shortCode: 'HST', expansion: 'Hawaii Standard Time' },
  { shortCode: 'AKST', expansion: 'Alaska Standard Time' },
  { shortCode: 'AKDT', expansion: 'Alaska Daylight Time' },
  { shortCode: 'AST', expansion: 'Atlantic Standard Time' },
  { shortCode: 'ADT', expansion: 'Atlantic Daylight Time' },
  { shortCode: 'NST', expansion: 'Newfoundland Standard Time' },
  { shortCode: 'NDT', expansion: 'Newfoundland Daylight Time' },
  { shortCode: 'BRST', expansion: 'Brasília Summer Time' },
  { shortCode: 'BRT', expansion: 'Brasília Time' },
  { shortCode: 'CLST', expansion: 'Chile Summer Time' },
  { shortCode: 'CLT', expansion: 'Chile Standard Time' },
  { shortCode: 'ART', expansion: 'Argentina Time' },
  { shortCode: 'WET', expansion: 'Western European Time' },
  { shortCode: 'CET', expansion: 'Central European Time' },
  { shortCode: 'EET', expansion: 'Eastern European Time' },
  { shortCode: 'MSK', expansion: 'Moscow Standard Time' },
  { shortCode: 'TRT', expansion: 'Turkey Time' },
  { shortCode: 'GST', expansion: 'Gulf Standard Time' },
  { shortCode: 'PKT', expansion: 'Pakistan Standard Time' },
  { shortCode: 'IST', expansion: 'Indian Standard Time' },
  { shortCode: 'NPT', expansion: 'Nepal Time' },
  { shortCode: 'UZT', expansion: 'Uzbekistan Time' },
  { shortCode: 'AFT', expansion: 'Afghanistan Time' },
  { shortCode: 'TMT', expansion: 'Turkmenistan Time' },
  { shortCode: 'TJT', expansion: 'Tajikistan Time' },
  { shortCode: 'YEKT', expansion: 'Yekaterinburg Time' },
  { shortCode: 'OMST', expansion: 'Omsk Standard Time' },
  { shortCode: 'KRAT', expansion: 'Krasnoyarsk Time' },
  { shortCode: 'IRKT', expansion: 'Irkutsk Time' },
  { shortCode: 'YAKT', expansion: 'Yakutsk Time' },
  { shortCode: 'VLAT', expansion: 'Vladivostok Time' },
  { shortCode: 'MAGT', expansion: 'Magadan Time' },
  { shortCode: 'PETT', expansion: 'Kamchatka Time' },
  { shortCode: 'KAMT', expansion: 'Kamchatka Time' },
  { shortCode: 'ANAT', expansion: 'Anadyr Time' },
  { shortCode: 'AEDT', expansion: 'Australian Eastern Daylight Time' },
  { shortCode: 'AEST', expansion: 'Australian Eastern Standard Time' },
  { shortCode: 'ACST', expansion: 'Australian Central Standard Time' },
  { shortCode: 'AWST', expansion: 'Australian Western Standard Time' },
  { shortCode: 'KST', expansion: 'Korea Standard Time' },
  { shortCode: 'JST', expansion: 'Japan Standard Time' },
  { shortCode: 'CST', expansion: 'China Standard Time' },
  { shortCode: 'NST', expansion: 'North Sumatra Time' },
  // Add more time zones and expansions as needed
];

export default timezones;
